import Navbar from '@/components/navbar'
import './globals.css'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Recipes App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <Navbar />
        <main className="flex flex-col items-center h-screen mt-20">
          {children}
        </main>
      </body>
    </html>
  )
}
